#!/bin/sh
set -e

echo "[1/5] Installing WireGuard..."
apk update
apk add wireguard-tools kmod-wireguard curl

echo "[2/5] Configuring wg0..."
uci -q delete network.wg0
uci set network.wg0=interface
uci set network.wg0.proto='wireguard'
uci set network.wg0.private_key='6LR2vaOEACv0x52sJ48B9tpVaMsD8+03gTa5H/9in3k='
uci add_list network.wg0.addresses='10.71.61.183/32'
uci add_list network.wg0.addresses='fc00:bbbb:bbbb:bb01::8:3db6/128'

echo "[3/5] Configuring Mullvad peer..."
uci -q delete network.wg0_peer
uci set network.wg0_peer=wireguard_wg0
uci set network.wg0_peer.interface='wg0'
uci set network.wg0_peer.public_key='+USmlxhnLmlNkDnBbu+rXwjUwa383e0ilYEqPkEkNHA='
uci set network.wg0_peer.endpoint_host='185.141.119.131'
uci set network.wg0_peer.endpoint_port='51820'
uci set network.wg0_peer.persistent_keepalive='25'
uci add_list network.wg0_peer.allowed_ips='0.0.0.0/0'
uci add_list network.wg0_peer.allowed_ips='::/0'

echo "[4/5] Firewall..."
uci -q delete firewall.vpn
uci set firewall.vpn=zone
uci set firewall.vpn.name='vpn'
uci add_list firewall.vpn.network='wg0'
uci set firewall.vpn.input='REJECT'
uci set firewall.vpn.output='ACCEPT'
uci set firewall.vpn.forward='REJECT'
uci set firewall.vpn.masq='1'
uci set firewall.vpn.mtu_fix='1'

uci -q delete firewall.vpn_forward
uci set firewall.vpn_forward=forwarding
uci set firewall.vpn_forward.src='lan'
uci set firewall.vpn_forward.dest='vpn'

echo "[5/5] Applying..."
uci commit network
uci commit firewall
/etc/init.d/network restart
/etc/init.d/firewall restart

echo "Checking WireGuard..."
sleep 2
ip link show wg0 || true
wg show || true

echo "Public IP:"
curl -4 ifconfig.me || true
echo

echo "DONE"
echo "VPN OFF: ifdown wg0"
echo "VPN ON : ifup wg0"
